# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

#require File.expand_path('../seed/users', __FILE__)
#require File.expand_path('../seed/countries', __FILE__)
#require File.expand_path('../seed/d11_teams', __FILE__)
#require File.expand_path('../seed/stadia', __FILE__)
#require File.expand_path('../seed/players', __FILE__)
#require File.expand_path('../seed/positions', __FILE__)
#require File.expand_path('../seed/teams', __FILE__)
#require File.expand_path('../seed/seasons', __FILE__)
#require File.expand_path('../seed/premier_leagues', __FILE__)
#require File.expand_path('../seed/match_days', __FILE__)
#require File.expand_path('../seed/matches', __FILE__)
#require File.expand_path('../seed/matches_whoscored_season_11', __FILE__)
#require File.expand_path('../seed/matches_last_few_match_days', __FILE__)
#require File.expand_path('../seed/goals', __FILE__)
#require File.expand_path('../seed/cards_yellow', __FILE__)
#require File.expand_path('../seed/cards_red', __FILE__)
#require File.expand_path('../seed/substitutions', __FILE__)
#require File.expand_path('../seed/d11_leagues', __FILE__)
#require File.expand_path('../seed/d11_match_days', __FILE__)
#require File.expand_path('../seed/d11_matches', __FILE__)
#require File.expand_path('../seed/player_match_stats', __FILE__)
#require File.expand_path('../seed/player_match_stats_goals_conceded', __FILE__)
#require File.expand_path('../seed/player_season_infos', __FILE__)
#require File.expand_path('../seed/player_season_stats', __FILE__)
#require File.expand_path('../seed/transfer_windows', __FILE__)
#require File.expand_path('../seed/transfer_days', __FILE__)
#require File.expand_path('../seed/transfer_listings', __FILE__)
#require File.expand_path('../seed/transfer_bids', __FILE__)
#require File.expand_path('../seed/transfers', __FILE__)
#require File.expand_path('../seed/team_registrations', __FILE__)
#require File.expand_path('../seed/d11_team_registrations', __FILE__)
#require File.expand_path('../seed/team_table_stats', __FILE__)
#require File.expand_path('../seed/d11_team_table_stats', __FILE__)
#require File.expand_path('../seed/team_match_squad_stats', __FILE__)
#require File.expand_path('../seed/team_season_squad_stats', __FILE__)
#require File.expand_path('../seed/d11_team_match_squad_stats', __FILE__)
#require File.expand_path('../seed/d11_team_season_squad_stats', __FILE__)
#require File.expand_path('../seed/player_career_stats', __FILE__)
#require File.expand_path('../seed/team_career_squad_stats', __FILE__)
#require File.expand_path('../seed/d11_team_career_squad_stats', __FILE__)
