d11_teams = [
    [ "None", "???", true ],
    [ "Andersson", "AND", false ],
    [ "Bolin/Gunnarsson", "B/G", false ],
    [ "Boman", "BOM", false ],
    [ "Egenfelt/Bengtsson", "E/B", false ],
    [ "Ekholm", "EKH", false ],
    [ "Solax", "SOL", false ],
    [ "Eriksson J", "ERJ", false ],
    [ "Eriksson M&D", "EMD", false ],
    [ "Eriksson/Fonsell", "E/F", false ],
    [ "Gröndahl", "GRD", false ],
    [ "Jakobsson", "JAK", false ],
    [ "Lindroos", "LIN", false ],
    [ "Mattsson", "MAT", false ],
    [ "Nyman", "NYM", false ],
    [ "Sirén", "SIR", false ],
    [ "Smeds", "SME", false ],
    [ "Sundström", "SUN", false ],
    [ "Wahlfors/Wiklund", "W/W", false ],
    [ "Viktorssons", "VIK", false ],
    [ "Witting", "WIT", false ],
    [ "Carlsson/Engblom", "C/E", false ],
    [ "Ekholm/Berndtsson", "EKB", false ],
    [ "Qvarnström", "QVA", false ],
    [ "Rosén/Ekstrand", "R/E", false ],
    [ "Carlsson/Brändström", "C/B", false ],
    [ "Hjalmarsson", "HJA", false ],
    [ "Eriksson M", "ERM", false ],
    [ "Grönholm", "GRH", false ],      
    [ "Lindholm", "LIH", false ],  
    [ "Engblom", "ENG", false ],
    [ "Sandberg", "SAN", false ],
    [ "Ehres", "EHR", false ],
    [ "Östergård", "ÖST", false ],
    [ "Egenfelt", "EGE", false ],
    [ "Smeds R", "SMR", false ],
    [ "Wiklund", "WIK", false ],
    [ "Örblom", "ÖRB", false ],    
    [ "Egenfelt/Eriksson", "E/E", false ],
    [ "Boijer", "BOI", false ],
    [ "Möller", "MÖL", false ],
    [ "Eriksson D", "ERD", false ],
    [ "Holmberg", "HOL", false ],
    [ "Karlsson", "KAR", false ],        
    [ "Jakobsson J", "JAJ", false ],
    [ "Kvarnström", "KVA", false ],
    [ "Eriksson/Jansson", "E/J", false ],
    [ "Eriksson N", "ERN", false ]
]

puts("Seeding d11_teams...")

d11_teams.each do | name, code, dummy |
  D11Team.create(name: name, code: code, dummy: dummy, owner_id: 1)
end
